import OpenAI from "openai";

const apiKey = process.env.GROK_API_KEY;

if (!apiKey) {
  throw new Error("Missing GROK_API_KEY in environment variables");
}

export const grok = new OpenAI({
  apiKey,
  baseURL: "https://api.x.ai/v1",
});

export interface GROKBriefInput {
  keyword: string;
  websiteUrl?: string;
  niche?: string;
}

export interface GROKBriefOutput {
  title: string;
  contentFormat: string;
  primaryAnswer: string;
  headingStructure: string[];
  keyQuestions: string[];
  schemaRecommendations: string[];
  eeatSignals: string[];
  citedSources: Array<{
    title: string;
    url: string;
    relevance: string;
  }>;
  geoScore: "Low" | "Medium" | "High";
  analysis: string;
}

export async function generateGeoBrief(
  input: GROKBriefInput
): Promise<GROKBriefOutput> {
  const systemPrompt = `You are a GEO (Generative Engine Optimization) expert. 
  Analyze how AI engines (ChatGPT, Perplexity, Google AI Overviews) currently answer a given keyword.
  Generate a structured GEO content brief optimized for AI citation.
  
  Return a valid JSON object with the following structure:
  {
    "title": "AI-optimized title",
    "contentFormat": "Description of best format (list, guide, definition, comparison, etc.)",
    "primaryAnswer": "The core answer AI engines should lift verbatim",
    "headingStructure": ["H2 heading 1", "H2 heading 2", ...],
    "keyQuestions": ["Question 1", "Question 2", ...],
    "schemaRecommendations": ["FAQ", "HowTo", "Article"],
    "eeatSignals": ["Author expertise signal", "Source credibility", ...],
    "citedSources": [{"title": "Source 1", "url": "url", "relevance": "Why it's cited"}],
    "geoScore": "Low|Medium|High",
    "analysis": "Brief explanation of why this content will be cited"
  }`;

  const userPrompt = `Generate a GEO content brief for this keyword: "${input.keyword}"${
    input.websiteUrl ? `\nWebsite: ${input.websiteUrl}` : ""
  }${input.niche ? `\nNiche: ${input.niche}` : ""}

Use web search to analyze current AI engine responses to this keyword.
Return ONLY valid JSON, no markdown formatting.`;

  try {
    const response = await grok.chat.completions.create({
      model: "grok-3",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.7,
      max_tokens: 2000,
      // web_search is enabled at the model level for grok-3
    });

    const content = response.choices[0].message.content;
    if (!content) {
      throw new Error("No content returned from Grok API");
    }

    // Extract JSON from the response
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON found in Grok response");
    }

    const brief = JSON.parse(jsonMatch[0]) as GROKBriefOutput;
    return brief;
  } catch (error) {
    console.error("Grok API error:", error);
    throw error;
  }
}

export function formatBriefAsMarkdown(brief: GROKBriefOutput): string {
  let markdown = `# ${brief.title}\n\n`;

  markdown += `## Quick Analysis\n`;
  markdown += `**GEO Score:** ${brief.geoScore}\n\n`;
  markdown += `${brief.analysis}\n\n`;

  markdown += `## Content Format\n`;
  markdown += `${brief.contentFormat}\n\n`;

  markdown += `## Primary Answer (AI Snapshot)\n`;
  markdown += `> ${brief.primaryAnswer}\n\n`;

  markdown += `## Recommended Structure\n`;
  brief.headingStructure.forEach((heading) => {
    markdown += `- ${heading}\n`;
  });
  markdown += `\n`;

  markdown += `## Key Questions to Answer\n`;
  brief.keyQuestions.forEach((question) => {
    markdown += `- ${question}\n`;
  });
  markdown += `\n`;

  markdown += `## E-E-A-T Signals to Include\n`;
  brief.eeatSignals.forEach((signal) => {
    markdown += `- ${signal}\n`;
  });
  markdown += `\n`;

  markdown += `## Schema Markup Recommendations\n`;
  brief.schemaRecommendations.forEach((schema) => {
    markdown += `- ${schema}\n`;
  });
  markdown += `\n`;

  markdown += `## Sources AI Currently Cites\n`;
  brief.citedSources.forEach((source, i) => {
    markdown += `${i + 1}. **${source.title}** - [${source.url}](${source.url})\n`;
    markdown += `   - Why cited: ${source.relevance}\n`;
  });
  markdown += `\n`;

  markdown += `---\n`;
  markdown += `*Generated by GEObrief.ai*\n`;

  return markdown;
}
